import { sql } from 'drizzle-orm';
import { date, integer, jsonb, pgTable, text, timestamp, varchar } from 'drizzle-orm/pg-core';
import { createInsertSchema } from 'drizzle-zod';

/**
 * User payment agreement table - manages Alipay/WeChat recurring deduction agreement information
 */
export const userAgreements = pgTable('user_agreements', {
  id: text('id')
    .primaryKey()
    .default(sql`gen_random_uuid()`),

  // User ID
  userId: text('user_id').notNull(),

  // ============ Agreement Information ============
  // Agreement number returned by Alipay
  agreementNo: varchar('agreement_no', { length: 64 }),
  // Merchant agreement number (generated by us, uniquely identifies user agreement)
  externalAgreementNo: varchar('external_agreement_no', { length: 64 }).unique().notNull(),
  // Sign-up scene, e.g. INDUSTRY|DIGITAL_MEDIA
  signScene: varchar('sign_scene', { length: 64 }).notNull(),
  // Sign-up channel: alipay | wechat
  signChannel: varchar('sign_channel', { length: 20 }).notNull(),

  // ============ Associated Subscription ============
  // Associated plan ID
  planId: text('plan_id').notNull(),
  // Plan slug (pro/ultra)
  planSlug: varchar('plan_slug', { length: 32 }).notNull(),
  // Plan name
  planName: varchar('plan_name', { length: 64 }).notNull(),
  // Billing interval: month/year
  billingInterval: varchar('billing_interval', { length: 10 }).notNull(),

  // ============ Deduction Rules ============
  // Single deduction amount (in cents)
  singleAmount: integer('single_amount').notNull(),
  // Period type: DAY/MONTH
  periodType: varchar('period_type', { length: 10 }).notNull(),
  // Number of periods
  period: integer('period').notNull(),
  // Next deduction date
  nextDeductDate: date('next_deduct_date'),

  // ============ Agreement Status ============
  // pending: awaiting sign-up, signed: signed, unsigned: terminated
  status: varchar('status', { length: 20 }).default('pending').notNull(),
  // Sign-up time
  signTime: timestamp('sign_time'),
  // Termination time
  unsignTime: timestamp('unsign_time'),
  // Termination reason: user_unsign (user initiated termination), merchant_unsign (merchant termination), expired (expired)
  unsignReason: varchar('unsign_reason', { length: 32 }),

  // ============ Deduction Status ============
  // Last deduction status: success/failed/pending
  lastDeductStatus: varchar('last_deduct_status', { length: 20 }),
  // Last deduction time
  lastDeductTime: timestamp('last_deduct_time'),
  // Last deduction order number
  lastDeductOrderNo: varchar('last_deduct_order_no', { length: 64 }),
  // Number of deduction failures today (for retry logic)
  deductFailCount: integer('deduct_fail_count').default(0),
  // Deduction failure reason
  deductFailReason: text('deduct_fail_reason'),

  // ============ Alipay User Information ============
  // Alipay user ID
  alipayUserId: varchar('alipay_user_id', { length: 64 }),
  // Alipay user OpenID
  alipayOpenId: varchar('alipay_open_id', { length: 128 }),
  // Alipay login account (desensitized)
  alipayLogonId: varchar('alipay_logon_id', { length: 64 }),

  // ============ Extended Information ============
  // First payment order number at sign-up
  firstOrderNo: varchar('first_order_no', { length: 64 }),
  // Other metadata
  metadata: jsonb('metadata'),

  // ============ Timestamps ============
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

export const insertUserAgreementSchema = createInsertSchema(userAgreements);

export type NewUserAgreement = typeof userAgreements.$inferInsert;
export type UserAgreementItem = typeof userAgreements.$inferSelect;
